name: Release on Tag

on:
  push:
    tags:
      - "*" # 监听所有 tag

permissions:
  contents: write  # 允许 GitHub Actions 访问 Releases API

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP archives and Generate metadata.json
        run: |
          mkdir archives
          METADATA_JSON="{"
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"

          for dir in template/*; do
            if [ -d "$dir" ]; then
              NAME=$(jq -r '.name' "$dir/package.json")
              DESCRIPTION=$(jq -r '.description' "$dir/package.json")
              ZIP_NAME="$(basename "$dir").zip"
              zip -r "archives/$ZIP_NAME" "$dir"

              METADATA_JSON+="\"$NAME\": { \"url\": \"$RELEASE_URL/$ZIP_NAME\", \"description\": \"$DESCRIPTION\" },"
            fi
          done

          # 去除最后一个逗号并关闭 JSON
          METADATA_JSON="${METADATA_JSON%,}"
          METADATA_JSON+="}"
          
          echo "$METADATA_JSON" > archives/metadata.json

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            archives/*.zip
            archives/metadata.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
