name: Release on Tag

on:
  push:
    tags:
      - "*" # 监听所有 tag

permissions:
  contents: write  # 允许 GitHub Actions 访问 Releases API

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP archives
        run: |
          mkdir archives
          for dir in template/*; do
            if [ -d "$dir" ]; then
              zip -r "archives/$(basename "$dir").zip" "$dir"
            fi
          done

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: archives/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
